packages:
  - 'apps/*'
  - 'packages/*'
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
  - cpu-features
  - esbuild
  - prisma
  - ssh2
  - tesseract.js
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  cpu-features: true
  esbuild: true
  prisma: true
  ssh2: true
  tesseract.js: true

